version: '3.8'
name: email-newsletter

services:
  app:
    build:
      context: .
      dockerfile: email.Dockerfile
    restart: always
    container_name: rust_server
    ports:
      - "${DOCKER_APP_PORT}:${APP_PORT}"
    networks:
      - front-tier
      - back-tier
    env_file: .env
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: psql_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PSWD}
    restart: always
    networks:
      - back-tier
    ports:
      - "${DOCKER_DB_PORT}:${DB_PORT}"
    volumes:
      - db-data:/var/lib/postgresql/data:Z
      - ./migrations:/migrations:Z

volumes:
  db-data:
    driver: local

configs:
  httpd-config:
    external: true

secrets:
  server-certificate:
    external: true

networks:
  front-tier: {}
  back-tier: {}
