application:
  port: 8083
database:
  database_name: "newsletter"
  username: "danescher98"
  password: 1234
email_rmq:
  sender_email: "danyiel5978@gmail.com"
  rmq_exchange: "subscribers"
  rmq_user: "guest"
  rmq_pswd: "guest"

